export { Home } from './Home/Home'
export { SingleFilmPage } from './SingleFilmPage/SingleFilmPage'
export { Favourites } from './Favourites/Favourites'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'